RailCommander/Controllers/BilletController.cs
using RailCommander.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RailCommander.Controllers
{
    public class BilletController : Controller
    {
        List<Station> mesStations = Models.Station.lesStations();

        // GET: Reservation
        public ActionResult Search()
        {
            //List<Station> myStation = new List<Station>();
            var query = (from station in mesStations
                         select station).ToList();

            if (query.Count() == 0)
            {
                return RedirectToAction("Home", "Home");
            }

            return View(query);
        }

        /*[HttpPost]
        public ActionResult Search()
        {

        }*/

        public String ReturnNom(String gareStartAjax, String gareEndAjax, String dateStartAjax, String dateReturnAjax, String hourStartAjax, String hourReturnAjax)
        {
            if (!String.IsNullOrEmpty(gareStartAjax) && !String.IsNullOrEmpty(gareEndAjax) && !String.IsNullOrEmpty(dateStartAjax) && !String.IsNullOrEmpty(dateReturnAjax) && !String.IsNullOrEmpty(hourStartAjax) && !String.IsNullOrEmpty(hourReturnAjax))
            {
                return "<div id='blocResult'>" + gareStartAjax + " " + gareEndAjax + " " + dateStartAjax + " " + dateReturnAjax + " " + hourStartAjax + " " + hourReturnAjax + "</div><br /><br /><input type='button' name='btnRechercherRetour' id='btnRechercherRetour' value='Suivant' />";
            }
            else
            {
                return "Vide";
            }

        }
    }
}

RailCommander/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RailCommander.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Home()
        {
            return View();
        }
    }
}

RailCommander/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Home";
}

<!-- Main -->

<div class="myBody">
    <div id="main">
        <div class="inner">
            <header>
                <h1>
                    Voyagez comme vous ne l'avez jamais fait.
                </h1>
                <p>Etiam quis viverra lorem, in semper lorem. Sed nisl arcu euismod sit amet nisi euismod sed cursus arcu elementum ipsum arcu vivamus quis venenatis orci lorem ipsum et magna feugiat veroeros aliquam. Lorem ipsum dolor sit amet nullam dolore.</p>
            </header>
            <section class="tiles">
                <article class="style1">
                    <span class="image">
                        <img src="../../Content/images/categorie1.jpg" alt="" />
                    </span>
                    <a href="@Url.Action("Search", "Billet")">
                        <h1>Reserver un billet</h1>
                        <div class="content">
                            <p>Reservation rapide et simple</p>
                        </div>
                    </a>
                </article>
                <article class="style2">
                    <span class="image">
                        <img src="../../Content/images/categorie2.jpg" alt="" />
                    </span>
                    <a href="">
                        <h1>Pass annuel</h1>
                        <div class="content">
                            <p>Gagnez du temps et de l'argent grâce à nos nombreux pass</p>
                        </div>
                    </a>
                </article>
                <article class="style3">
                    <span class="image">
                        <img src="../../Content/images/categorie3.jpg" alt="" />
                    </span>
                    <a href="">
                        <h1>Bon plans</h1>
                        <div class="content">
                            <p>Des trajets à prix réduits pour tous, tout le temps</p>
                        </div>
                    </a>
                </article>
                <article class="style4">
                    <span class="image">
                        <img src="../../Content/images/pic04.jpg" alt="" />
                    </span>
                    <a href="generic.html">
                        <h2>Tempus</h2>
                        <div class="content">
                            <p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
                        </div>
                    </a>
                </article>
                <article class="style5">
                    <span class="image">
                        <img src="../../Content/images/pic05.jpg" alt="" />
                    </span>
                    <a href="generic.html">
                        <h2>Aliquam</h2>
                        <div class="content">
                            <p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
                        </div>
                    </a>
                </article>
                <article class="style6">
                    <span class="image">
                        <img src="../../Content/images/pic06.jpg" alt="" />
                    </span>
                    <a href="generic.html">
                        <h2>Veroeros</h2>
                        <div class="content">
                            <p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
                        </div>
                    </a>
                </article>
            </section>
        </div>
    </div>
</div>